version: '3'
services:
  android-container-1:
    image: budtmo/docker-android:emulator_13.0
    ports:
      - "5901:5900"
      - "6081:6080"
      - "8081:8081"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm
    volumes:
      - /home/idrbt/android-app:/app/android-app
    container_name: android-container-1

  novnc-container:
    image: dougw/novnc
    environment:
      - REMOTE_HOST=192.168.138.123
      - REMOTE_PORT=5901
    ports:
      - "8080:8080"
    container_name: novnc-container
